#!/bin/bash
#
# Wrapper script that ensures we'll run the required version.
# If the required version is on the PATH, just use that.
# If not, download and build a local version and use that.
#
set -e
BASEDIR=$(cd `dirname $0` && /bin/pwd)
REQUIRED_COREUTILS_VERSION=8.13
PATH=$BASEDIR/coreutils-$REQUIRED_COREUTILS_VERSION/temp:$PATH
TIMEOUT_VERSION=`timeout --version | grep ^timeout | sed 's/^.* //'`

echo required timeout version = ${REQUIRED_COREUTILS_VERSION}
echo installed timeout = ${TIMEOUT_VERSION}

if [ "$REQUIRED_COREUTILS_VERSION" != "$TIMEOUT_VERSION" ] ; then
  pushd $BASEDIR
    echo "****** DOWNLOADING coreutils-$REQUIRED_COREUTILS_VERSION"
    curl --silent --location ftp://ftp.gnu.org/gnu/coreutils/coreutils-$REQUIRED_COREUTILS_VERSION.tar.gz | tar zx
    echo "****** BUILDING coreutils-$REQUIRED_COREUTILS_VERSION"
    pushd coreutils-$REQUIRED_COREUTILS_VERSION
      ./configure
      make
      make install
    popd
  popd
fi
